# Rules for generating parsers using ANTLR3.

def _antlr_srcjar_impl(ctx):
  src_jar = ctx.outputs.src_jar
  args = ["-o", src_jar.path] + [src.path for src in ctx.files.srcs]

  # Invoke our custom AntlrCompiler.
  ctx.action(
      inputs = ctx.files.srcs,
      outputs = [src_jar],
      mnemonic = "antlr",
      executable = ctx.executable._antlr,
      arguments = args,
  )

# Provides a srcjar with the sources generated by ANTLR. The rule should be used as part of the
# srcs in a java_library.
antlr_sources = rule(
    attrs = {
        "srcs": attr.label_list(
            non_empty = True,
            allow_files = True,
        ),
        "_antlr": attr.label(
            executable = True,
            cfg = "host",
            default = Label("//tools/base/bazel:antlr"),
            allow_files = True,
        ),
    },
    outputs = {
        "src_jar": "%{name}.srcjar",
    },
    implementation = _antlr_srcjar_impl,
)
