## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the Android Instant App SDK. This is only used by Gradle.
aia.repo=${escapePropertyValue(instantAppSdkDir)}/maven-repo