cc_library(
    name = "slicer",
    srcs = [
        "dex_bytecode.cc",
        "dex_format.cc",
        "dex_utf8.cc",
        "slicer.cc",
    ],
    hdrs = [
        "dex_bytecode.h",
        "dex_format.h",
        "dex_leb128.h",
        "dex_utf8.h",
        "slicer.h",
    ],
    visibility = ["//visibility:public"],
)
