exports_files(["NoOpTest.java"])

filegroup(
    name = "iml_to_bazel",
    srcs = glob(["iml_to_bazel/**"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "local_maven_repository_generator",
    srcs = glob(["local_maven_repository_generator/**"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "pom_generator",
    srcs = glob(["pom_generator/**"]),
    visibility = ["//visibility:public"],
)
