java_binary(
    name = "dev-sdk-updater",
    srcs = ["src/com/android/tools/utils/DevSdkUpdater.java"],
    main_class = "com.android.tools.utils.DevSdkUpdater",
    deps = ["//tools/base/sdklib"],
)
