load("//tools/base/bazel:kotlin.bzl", "kotlin_library")

package(default_visibility = ["//visibility:public"])

kotlin_library(
    name = "live-store-protocol",
    srcs = glob([
        "src/**/*.kt",
    ]),
    deps = [
        "//tools/idea/.idea/libraries:gson",
    ],
)
