cc_library(
    name = "testutils",
    srcs = [
        "utils.bazel.cc",
        "utils.h",
    ],
    hdrs = [
        "utils.h",
    ],
    copts = [
        "-Itools/base/transport/native/daemon",
    ],
    include_prefix = "test",
    tags = ["no_windows"],
    visibility = ["//visibility:public"],
)
