load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "studio.intellij.android.wizardTemplate.impl",
    srcs = ["src"],
    iml_files = ["intellij.android.wizardTemplate.impl.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/base/wizard/template-plugin:studio.intellij.android.wizardTemplate.plugin[module]",
        "//tools/idea/.idea/libraries:kotlin-stdlib-jdk8",
    ],
)
