cc_binary(
    name = "dexter",
    srcs = [
        "dexter.cc",
        "dexter.h",
        "main.cc",
    ],
    copts = [
        "-Itools/base/profiler/native/dex",
    ],
    deps = [
        "//tools/base/profiler/native/dex/slicer",
    ],
)
