java_library(
    name = "instant-run-runtime",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    javacopts = ["-extra_checks:off"],
    visibility = ["//visibility:public"],
    deps = [
        "//tools/base/annotations",
        "//tools/base/instant-run:instant-run-common",
    ],
)
