load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "studio.layout-inspector-common",
    srcs = ["src/main"],
    iml_files = ["layout-inspector-common.iml"],
    project = "unb",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/adt/idea/.idea/libraries:kotlin-stdlib-jdk8",
        "//tools/adt/idea/.idea/libraries:studio-proto",
        "//tools/adt/idea/.idea/libraries:Guava",
        "//tools/adt/idea/.idea/libraries:layoutinspector-skia-proto",
    ],
)
