cc_library(
    name = "perfd_internal_headers",
    hdrs = [
        "daemon.h",
        "profiler_component.h",
        "profiler_service.h",
    ],
    copts = [
        "-Itools/base/profiler/native",
        "-I$(GENDIR)/tools/base/profiler",
    ],
    visibility = ["//visibility:public"],
)
