load("//tools/base/bazel:bazel.bzl", "iml_module")

java_library(
    name = "agent_callback",
    srcs = glob([
        "src/**/*.java",
    ]),
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
iml_module(
    name = "studio.android.sdktools.threading-agent-callback",
    srcs = ["src"],
    iml_files = ["android.sdktools.threading-agent-callback.iml"],
    visibility = ["//visibility:public"],
)
