java_library(
    name = "test-inspector-api",
    srcs = glob(["src/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//prebuilts/tools/common/m2:androidx.annotation.annotation.1.1.0",
    ],
)
