filegroup(
    name = "linux_start_script",
    srcs = ["linux_start_script.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "mac_start_script",
    srcs = ["mac_start_script.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "win_start_script",
    srcs = ["win_start_script.bat"],
    visibility = ["//visibility:public"],
)
