package(default_visibility = ["//visibility:public"])

filegroup(
    name = "utils",
    srcs = glob(["utils/**"]),
)

filegroup(
    name = "perfd/cpu",
    srcs = glob(["perfd/cpu/**"]),
)

filegroup(
    name = "perfd/memory",
    srcs = glob(["perfd/memory/**"]),
)

filegroup(
    name = "perfd/network",
    srcs = glob(["perfd/network/**"]),
)

filegroup(
    name = "perfd/graphics",
    srcs = glob(["perfd/graphics/**"]),
)
