Output: report.json
Trace-Agent: false
Annotation: java.lang.Deprecated
Start: com.android.tools.tracer.MainTest::main
Trace: com.android.tools.tracer.MainTest::simple
Trace: com.android.tools.tracer.MainTest::twoReturns
Trace: com.android.tools.tracer.MainTest::itThrows
Trace: com.android.tools.tracer.MainTest::itCatches
Trace: com.android.tools.tracer.MainTest::callsAThrow
Trace: com.android.tools.tracer.Other
Trace: com.android.tools.tracer.pkg.*
Flush: com.android.tools.tracer.MainTest::main
