package(default_visibility = ["//visibility:public"])

# any extra files needed by the toolchains, e.g. wrapper scripts.
filegroup(
    name = "extra_files",
    srcs = [
        "darwin/wrapped_ar",
    ],
)
