load("//tools/base/bazel:proto.bzl", "java_proto_library")
load("//tools/base/bazel:maven.bzl", "maven_java_library", "maven_pom")

java_proto_library(
    name = "proto",
    srcs = glob(["src/**/*.proto"]),
    visibility = ["//visibility:public"],
)
