java_library(
    name = "device-provider",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        "//tools/base/annotations",
        "//tools/base/build-system:gradle-api_neverlink",
        "//tools/base/build-system:tools.builder-test-api",
        "//tools/base/build-system/builder",
        "//tools/base/build-system/gradle-core",
        "//tools/base/build-system/gradle-experimental",
        "//tools/base/common:tools.common",
        "//tools/base/third_party:com.google.guava_guava",
    ],
)
