load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "studio.chunkio",
    srcs = ["src/main/java"],
    iml_files = ["chunkio.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
