load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "studio.android.sdktools.chunkio",
    srcs = ["src/main/java"],
    iml_files = ["android.sdktools.chunkio.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:KotlinJavaRuntime"],
)
